-- ============================================================
--  FILE             : aggregate_functions_sum_count_avg_max_min.sql
--  TOPIC            : Aggregate Functions — SUM, COUNT, AVG, MAX, MIN
--  LEARNING OBJECTIVE: Understand how each aggregate function
--                      summarizes data, how COUNT behaves
--                      differently with *, column, and literal
--                      values, and how to write comments that
--                      accurately match the query logic
--  ROADMAP          : Day 7 - programmingvalley.com 30-Day SQL Roadmap
--  LEARNER          : Muhammad Ali
-- ============================================================


-- ============================================================
-- MISTAKES MADE & LESSONS LEARNED
-- ============================================================
-- MISTAKE 1: USE sql_learninng; — typo (extra "n")
--   Always double-check the USE statement first — every
--   later query depends on it being correct.
--
-- MISTAKE 2: COUNT("James Murray") to find a specific customer
--   COUNT(literal text) does NOT search for that text anywhere.
--   It treats the text as a constant and counts every row where
--   that constant is non-null — which is always every row.
--   This returns the SAME result as COUNT(*) — it does not
--   filter by the customer at all.
--   RULE: To count occurrences of a specific value, you must
--   use WHERE, not put the value inside COUNT().
--
-- MISTAKE 3: LIKE '%James Murray%' for an exact name match
--   Works, but is loose — would also match "James Murray Jr."
--   or any name containing that text anywhere.
--   For an EXACT match, use = instead of LIKE.
--   LIKE is for genuine partial/pattern matching only.
--
-- MISTAKE 4: Comment said "avg" but query used SUM
--   Comments must accurately describe what the query and alias
--   actually compute. A mismatch confuses anyone reading the code.
-- ============================================================


USE sql_learning;


-- ============================================================
-- STEP 1: VIEW DATA
-- ============================================================

SELECT * FROM sales_data;


-- ============================================================
-- STEP 2: SUM — Total Net Sales Per Segment
-- ============================================================

-- BUSINESS QUESTION:
-- "What is the total sales amount generated by each segment?"

SELECT
    segment,
    SUM(net_sales) AS total_sales
FROM sales_data
GROUP BY segment;


-- ============================================================
-- STEP 3: COUNT(*) — Total Orders Per Region
-- ============================================================

-- BUSINESS QUESTION:
-- "How many total orders came from each region?"

SELECT
    region,
    COUNT(*) AS total_orders
FROM sales_data
GROUP BY region;


-- ============================================================
-- STEP 4: AVG — Average Profit/Loss Per Segment
-- ============================================================

-- BUSINESS QUESTION:
-- "On average, is each segment making profit or loss?"

SELECT
    segment,
    AVG(profit_loss) AS avg_profit_loss
FROM sales_data
GROUP BY segment;


-- ============================================================
-- STEP 5: MAX and MIN Together — Profit/Loss Range Per Region
-- ============================================================

-- BUSINESS QUESTION:
-- "What is the best and worst profit/loss recorded in each
--  region? I want to see how volatile each region's
--  performance is."

SELECT
    region,
    MAX(profit_loss) AS max_profit_loss,
    MIN(profit_loss) AS min_profit_loss
FROM sales_data
GROUP BY region;


-- ============================================================
-- STEP 6: COUNT — Finding a Specific Customer (Corrected)
-- ============================================================

-- BUSINESS QUESTION:
-- "How many orders has the customer James Murray placed?"
SELECT COUNT(*) AS james_total
FROM sales_data
WHERE customer_name = 'James Murray';

-- ALTERNATE — pattern match with LIKE
-- Use LIKE only when genuine partial matching is needed
-- (e.g., unsure of exact spelling, or searching for a fragment)
SELECT COUNT(*) AS james_total
FROM sales_data
WHERE customer_name LIKE '%James Murray%';


-- ============================================================
-- STEP 7: SUM — Total Customers Served Per Segment
-- ============================================================

-- BUSINESS QUESTION:
-- "What is the total number of customers served, broken
--  down by segment?"

SELECT
    segment,
    SUM(no_customers) AS total_customers
FROM sales_data
GROUP BY segment;


-- ============================================================
-- STEP 8: AVG — Average Customers Per Order, By Region (Corrected)
-- ============================================================

-- BUSINESS QUESTION:
-- "On average, how many customers are involved per order
--  in each region?"

SELECT
    region,
    AVG(no_customers) AS avg_customers
FROM sales_data
GROUP BY region;

-- If TOTAL (not average) customers per region was actually
-- needed instead, this would be the correct version:
SELECT
    region,
    SUM(no_customers) AS total_customers
FROM sales_data
GROUP BY region;


-- ============================================================
-- INTERVIEW QUESTIONS — AGGREGATE FUNCTIONS
-- ============================================================

-- Q1: What is the difference between COUNT(*) and COUNT(column)?
-- A : COUNT(*) counts all rows, including rows with NULL values
--     in any column. COUNT(column) counts only rows where that
--     specific column is NOT NULL.

-- Q2: What does COUNT("some text") actually do?
-- A : It treats the text as a constant value, not a search
--     term. Since the constant is always non-null, it counts
--     every row — identical to COUNT(*). It does NOT filter
--     by that text. To search for a specific value, use WHERE.

-- Q3: When should you use LIKE vs = for matching text?
-- A : Use = for an exact, known match (faster, precise).
--     Use LIKE only when you need partial/pattern matching,
--     e.g., unsure of exact spelling or searching for a fragment
--     within a larger string.

-- Q4: What is the difference between SUM and AVG?
-- A : SUM adds up all values in a group (total).
--     AVG calculates the mean (total divided by count).
--     Choosing the wrong one gives a technically valid but
--     business-meaningless result — always match the function
--     to what's actually being asked.

-- Q5: Can you use MAX and MIN in the same query?
-- A : Yes. Combining them is common for finding the range
--     (spread) of values within each group — useful for
--     spotting volatility or extremes in business data.