-- ============================================================
--  FILE             : day8_mini_project_hospital_operations_report.sql
--  PROJECT          : MediCare Network — Hospital Operations Report
--  COMPANY          : MediCare Network
--  ROLE             : Data Analyst
--  SKILLS USED      : GROUP BY (single + multi-column), SUM,
--                     COUNT, AVG, ORDER BY + LIMIT for individual
--                     extremes, recognizing/answering ambiguous
--                     business questions explicitly
--  ROADMAP          : Day 8 - programmingvalley.com 30-Day SQL Roadmap
--  DATASET          : hospital_db (patients, doctors, appointments,
--                     billing, hospitals)
--  LEARNER          : Muhammad Ali
-- ============================================================



USE hospital_db;


-- ============================================================
-- Report 1: Department load — patients and treatment cost
-- ============================================================

-- BUSINESS QUESTION:
-- How many patients does each department currently have, and
--  what is the total treatment cost generated by each
--  department? I want both numbers in one report.

SELECT
    Department,
    COUNT(*)             AS total_patients,
    SUM(Treatment_Cost)  AS total_treatment_cost
FROM patients
GROUP BY Department;


-- ============================================================
-- Report 2: Doctor distribution per department
-- ============================================================

-- BUSINESS QUESTION:
-- For each department, how many doctors do we have, and what
--  is their average years of experience?

SELECT
    Department,
    COUNT(*)                       AS total_doctors,
    AVG(Experience_Years)          AS average_years_of_experience
FROM doctors
GROUP BY Department;


-- ============================================================
-- Report 3: Appointments by department and status
-- ============================================================

-- BUSINESS QUESTION:
-- Break down appointments by department AND status together.
--  How many 'Emergency' appointments are 'Scheduled' vs
--  'Cancelled'?

SELECT
    Department,
    Status,
    COUNT(*) AS total_appointments
FROM appointments
GROUP BY Department, Status;


-- ============================================================
-- Report 4: Billing risk by payment status
-- ============================================================

-- BUSINESS QUESTION:
-- Group billing by Payment_Status. Show total Patient_Payable
--  amount outstanding for each status — specifically how much
--  money is sitting in 'Pending' payments company-wide.

SELECT
    Payment_Status,
    SUM(Patient_Payable) AS total_payable_amount
FROM billing
GROUP BY Payment_Status;


-- ============================================================
-- Report 5: City-level hospital bed capacity
-- ============================================================

-- BUSINESS QUESTION:
-- For each city, what is the total number of beds across all
--  our hospitals there?

SELECT
    City,
    SUM(Beds) AS total_beds
FROM hospitals
GROUP BY City;


-- ============================================================
-- Report 6: Patient outcomes by gender (corrected)
-- ============================================================

-- BUSINESS QUESTION:
-- For each combination of Gender and Outcome, how many
--  patients fall into that group? I want to see if outcomes
--  differ noticeably between genders.

SELECT
    Gender,
    Outcome,
    COUNT(*) AS total_patients
FROM patients
GROUP BY Gender, Outcome;


-- ============================================================
-- Report 7: Two separate questions, clearly labeled
-- ============================================================

-- BUSINESS QUESTION (PART A — Individual doctor):
-- Tell me the ONE doctor in our entire system with the most
--  years of experience — name, department, city, exact years.
--
-- This is an INDIVIDUAL extreme value question — full row
-- details needed. Use ORDER BY + LIMIT 1, no GROUP BY.

SELECT
    Doctor_Name,
    Department,
    City,
    Experience_Years
FROM doctors
ORDER BY Experience_Years DESC
LIMIT 1;


-- BUSINESS QUESTION (PART B — Department-level average):
-- Which ONE department has the highest average doctor
--  experience?
--
-- This is a GROUP-level average question — GROUP BY + AVG,
-- then sort and limit to the single highest department.

SELECT
    Department,
    AVG(Experience_Years) AS avg_experience
FROM doctors
GROUP BY Department
ORDER BY avg_experience DESC
LIMIT 1;


-- ============================================================
-- Report 8: Highest-cost department
-- ============================================================

-- BUSINESS QUESTION:
-- Which single department generates the highest total
--  Treatment_Cost across all patients? Department name and
--  total figure, ranked so the highest is unmistakably on top.

SELECT
    Department,
    SUM(Treatment_Cost) AS total_treatment_cost
FROM patients
GROUP BY Department
ORDER BY total_treatment_cost DESC
LIMIT 1;


-- ============================================================
-- KEY LESSONS FROM THIS PROJECT
-- ============================================================
-- 1. Never add a WHERE filter that wasn't explicitly requested.
--    An unrequested filter silently produces a wrong-but-
--    believable answer — the most dangerous kind of mistake.
--
-- 2. The phrase "combination of X and Y" in a business question
--    is a direct signal for GROUP BY X, Y together — every
--    listed column must be grouped or aggregated.
--
-- 3. When a question contains TWO distinct asks (an individual
--    extreme AND a group average), answer them as two separate,
--    clearly labeled queries rather than forcing one query to
--    do both jobs.
--
-- 4. "Individual extreme value, full row" = ORDER BY + LIMIT 1
--    "Group-level extreme average" = GROUP BY + AVG + ORDER BY
--    + LIMIT 1 — these are different tools for different
--    questions, never interchangeable.
-- ============================================================